from typing import Protocol
from uuid import UUID

from app.domain.shift_standards import ShiftStandard

from .dto import ShiftStandardListQuery


class ShiftStandardRepository(Protocol):
    def create_shift_standard(self, item: ShiftStandard) -> ShiftStandard: ...
    def get_shift_standard(self, item_id: UUID) -> ShiftStandard | None: ...
    def update_shift_standard(self, item: ShiftStandard) -> ShiftStandard | None: ...
    def delete_shift_standard(self, item_id: UUID) -> bool: ...
    def list_shift_standards(self, query: ShiftStandardListQuery) -> list[ShiftStandard]: ...
