services:

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - ok_network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

  alertmanager:
    image: prom/alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./monitoring:/etc/alertmanager

    networks:
      - ok_network


  alembic:
    build: .
    command: bash -c "alembic upgrade head && echo 'Migrations completed successfully' || exit 1"    
    volumes:
      - .:/app
    networks:
      - ok_network

  test:
    build: .
    command: bash -c "pytest --maxfail=3 --disable-warnings || exit 1"
    depends_on:
      - alembic
    networks:
      - ok_network
    volumes:
      - .:/app
      - ./tests:/app/tests
    environment:
      - PYTHONPATH=/app


  web:
    tty: true
    stdin_open: true
    build: .
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "${FLASK_PORT}:8000"
    environment:
      - HTTP_PROXY=
      - HTTPS_PROXY=
    depends_on:
      - alembic
      - test
    volumes:
      - .:/app
    command: gunicorn -c gunicorn.conf.py run:app
    networks:
      - ok_network

volumes:
  grafana-storage:

networks:
  ok_network:
    external: true

