services:

  web:
    tty: true
    stdin_open: true
    build: .
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "${FLASK_PORT}:8000"
    environment:
      - HTTP_PROXY=
      - HTTPS_PROXY=
    volumes:
      - .:/app
      - ./logs:/app/logs  # ✅ сохраняем логи на хосте
    command: gunicorn -c gunicorn.conf.py run:app
    networks:
      - ok_network

networks:
  ok_network:
    external: true
