services:

  web:
    image: "${IMAGE_NAME}:${TAG}"  # <--- вот оно, магия!
    tty: true
    stdin_open: true
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "${FLASK_PORT}:8000"
    environment:
      - HTTP_PROXY=
      - HTTPS_PROXY=
    volumes:
      - ./logs:/app/logs
    command: gunicorn -c gunicorn.conf.py run:app
    networks:
      - ok_network

networks:
  ok_network:
    external: true
