services:
  generate_keys:
    build: .
    command: python generate_keys.py
  volumes:
      - .:/app
    networks:
      - ok_network

  alembic:
    build: .
    command: alembic upgrade head  
    depends_on:
      - generate_keys 
    volumes:
      - .:/app
    networks:
      - ok_network

  test:
    build: .
    command: pytest --maxfail=3 --disable-warnings
    depends_on:
      - alembic
      - generate_keys
    networks:
      - ok_network
    volumes:
      - .:/app
      - ./tests:/app/tests
    environment:
      - PYTHONPATH=/app


  web:
    tty: true
    stdin_open: true
    build: .
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    environment:
      - HTTP_PROXY=
      - HTTPS_PROXY=
    depends_on:
      - alembic
      - test
    volumes:
      - .:/app
    command: gunicorn -c gunicorn.conf.py run:app
    networks:
      - ok_network

networks:
  ok_network:
    driver: bridge
