services:

  web:
    image: ${DOCKERHUB_USERNAME}/ok-service-backend:${TAG}
    tty: true
    stdin_open: true
    restart: always
    ports:
      - "${FLASK_PORT}:8000"
    environment:
      - HTTP_PROXY=
      - HTTPS_PROXY=
    volumes:
      - ./logs:/app/logs
      - .env:/app/.env 
    command: gunicorn -c gunicorn.conf.py run:app
    networks:
      - ok_network

  template-service:
    image: ${DOCKERHUB_USERNAME}/template-service:latest
    container_name: template-service
    tty: true
    stdin_open: true
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs  
      - .env:/app/.env 
    networks:
      - ok_network

networks:
  ok_network:
    external: true
