services:
  alembic:
    build: .
    command: bash -c "alembic upgrade head && echo 'Migrations completed successfully' || exit 1"    
    volumes:
      - .:/app
    networks:
      - ok_network

  test:
    build: .
    command: bash -c "pytest --maxfail=3 --disable-warnings || exit 1"
    depends_on:
      - alembic
    networks:
      - ok_network
    volumes:
      - .:/app
      - ./tests:/app/tests
    environment:
      - PYTHONPATH=/app


  web:
    tty: true
    stdin_open: true
    build: .
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    environment:
      - HTTP_PROXY=
      - HTTPS_PROXY=
    depends_on:
      - alembic
      #- test
    volumes:
      - .:/app
    command: gunicorn -c gunicorn.conf.py run:app
    networks:
      - ok_network

networks:
  ok_network:
    driver: bridge
