global:
  resolve_timeout: 5m

route:
  receiver: 'default'

receivers:
  - name: 'default'
    # Пока просто лог, можно позже сюда Slack или Telegram прикрутить
    webhook_configs:
      - url: 'http://localhost:8000/debug-alert'  # пока-заглушка
        send_resolved: true


