global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask_app'
    static_configs:
      - targets: ['web:8000']
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
      
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']