from __future__ import annotations

from typing import Protocol
from uuid import UUID

from app.domain.projects import Project, ProjectStatus

from .dto import ProjectActor, ProjectListQuery, ProjectStatsMap


class ProjectRepository(Protocol):
    def create_project(self, project: Project) -> Project: ...

    def get_project(self, project_id: UUID) -> Project | None: ...

    def get_project_record(self, project_id: UUID) -> dict[str, object] | None: ...

    def update_project(self, project: Project) -> Project | None: ...

    def delete_project(self, project_id: UUID) -> bool: ...

    def list_projects(self, query: ProjectListQuery, actor: ProjectActor) -> list[Project]: ...

    def list_project_records(
        self, query: ProjectListQuery, actor: ProjectActor
    ) -> list[dict[str, object]]: ...

    def get_project_stats(self, project_id: UUID) -> ProjectStatsMap: ...

    def get_project_stats_by_materials(self, project_id: UUID) -> ProjectStatsMap: ...

    def get_project_leader_stats(self, project_leader_id: UUID) -> dict[str, object]: ...

    def get_project_leader_stats_details(self, project_leader_id: UUID) -> dict[str, object]: ...

    def update_project_status(
        self, project_id: UUID, expected_status: ProjectStatus, status: ProjectStatus
    ) -> Project | None: ...
