from __future__ import annotations

from typing import Protocol, TYPE_CHECKING
from uuid import UUID

from app.domain.acceptances import Acceptance, AcceptanceStatusHistory
if TYPE_CHECKING:
    from .use_cases import AcceptanceListQuery


class AcceptanceRepository(Protocol):
    def create_acceptance(self, acceptance: Acceptance) -> Acceptance: ...
    def get_acceptance(self, acceptance_id: UUID) -> Acceptance | None: ...
    def update_acceptance(self, acceptance: Acceptance) -> Acceptance | None: ...
    def update_acceptance_with_status_history(
        self, acceptance: Acceptance, history: AcceptanceStatusHistory
    ) -> Acceptance | None: ...
    def delete_acceptance(self, acceptance_id: UUID) -> bool: ...
    def list_acceptances(self, query: AcceptanceListQuery) -> list[Acceptance]: ...
    def list_acceptance_history(self, query) -> list[AcceptanceStatusHistory]: ...
